package ProgressBarPack;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nil_b
 */
public class ProgressBarComponentJD extends javax.swing.JDialog {
private int[] itens;
private String objeto="";
    /**
     * Creates new form ProgressBarComponentJD
     */
    public ProgressBarComponentJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProgressBarComponentJD dialog = new ProgressBarComponentJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
      public void exportarExcel( ){
          
      ProgressBarGeneric pbg = new ProgressBarGeneric();
//        if(jbtPesquisar.isSelected() == true && JtableListagemDadosArquivo.getRowCount() > 0){
//            
//            exportarJtable.exportarJtable(JtableListagemDadosArquivo);
//            
//         //   controller.importExcelToJtableJava(pegaDirPadrao, PegaobjetoFileNameExtensionFilter, TITLE_PROPERTY);
//            
//                    }else if(jbtPesquisar.isSelected() == false && jTableDadosModel.getRowCount() > 0 ){
//                     exportarJtable.exportarJtable(jTableDadosModel);
//            }else {
//            JOptionPane.showMessageDialog(null, "Não há dados listados para exportar", "Aviso do Sistema", JOptionPane.INFORMATION_MESSAGE);
//            }
//        }


      
     class ExcluirEmMassaThread extends Thread {
         public void ExcluirEmMassaThread(int[] itensUsuer){
          itens = itensUsuer;
         
         }
        public void run() {
                int arreioDeLinhaSelecionadas[] = itens;
                int jColunnTable = 0;
                int jColunnTableNome = 1;
                  for(int t =0; t < arreioDeLinhaSelecionadas.length;t++){
                      
                      int k = arreioDeLinhaSelecionadas[t];
//                      Object objetoResgatado     = jTableDadosModel.getValueAt(k, jColunnTable);
//                      Object objetoResgatadoNome = jTableDadosModel.getValueAt(k, jColunnTableNome);
                      int codigo = Integer.parseInt(objetoResgatado.toString());
                pbg.RunProgress(0, arreioDeLinhaSelecionadas.length, t, objetoResgatadoNome.toString());
                   //   controllerDao.ExcluirLote(Categoria.class, codigo);
             }
       //  jTableDadosModel.clearSelection();
       /// puxarparametro(0,"Sim");
      //  ComportamentoAtualizar();
        // jDialogBarraDeProgresso2.getOwner().dispose();
        this.stop();
       
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
