/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetodebolso;


import infra.ti.lerDadosDDL;
import infra.ti.lerDadosSystem;
import infra.ti.lerDadosDebug;
import infra.ti.WrConfs;
import infra.ti.lerDadosTi;
import infra.ti.escritaDadosDebug;
import infra.ti.escritaDadosC3pO;
import infra.ti.escritaDadosDDL;
import java.awt.EventQueue;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;

import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nil_b
 */
public class ConfigBDView extends JPanel {
           private static JFrame frameConfigBDView;
           public static String  strDriverBd;  
           public static String  strJdbc;  
 public static  String bshowsql = null;
 public static String bforsql;
 public static String gs ;
 public static String usqc;
              
          
public static Map mapDb = new HashMap();
    /**
     * Creates new form ConfigBDView
     */
             

    public ConfigBDView() {
        initComponents();
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtextUrl = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtextUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jpassSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jtextDataBase = new javax.swing.JTextField();
        jtextPorta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtext_jdbc = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtext_mas_size = new javax.swing.JTextField();
        jtext_Min_Size = new javax.swing.JTextField();
        jtext_Time_Out = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtext_Max_Stat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtext_Idle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcb_USC = new javax.swing.JComboBox<>();
        jcb_GS = new javax.swing.JComboBox<>();
        jcb_Format_Sql = new javax.swing.JComboBox<>();
        jcb_Show_Sql = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcb_ddl = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcb_operacao_ddl = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jbt_salvarConf = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBasico = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jTextField7.setText("jTextField7");

        jPopupMenu3.setComponentPopupMenu(jPopupMenu3);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Driver:");

        jtextUrl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextUrlActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Seleciona o Driver Correspondente ao Servidor->", "com.mysql.jdbc.Driver", "com.mysql.cj.jdbc.Driver", "org.postgresql.Driver", "org.firebirdsql.jdbc.FBDriver" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");

        jtextUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ip/Dns:");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Selecione um Dialeto->", "org.hibernate.dialect.FirebirdDialect", "org.hibernate.dialect.MySQLDialect", "org.hibernate.dialect.MySQL57Dialect", "org.hibernate.dialect.MySQL8Dialect", "org.hibernate.dialect.PostgreSQL81Dialect", "org.hibernate.dialect.PostgreSQL82Dialect", "org.hibernate.dialect.PostgreSQL9Dialect", "org.hibernate.dialect.PostgreSQL91Dialect", "org.hibernate.dialect.PostgreSQL92Dialect", "org.hibernate.dialect.PostgreSQL93Dialect", "org.hibernate.dialect.PostgreSQL94Dialect", "org.hibernate.dialect.PostgreSQL95Dialect " }));

        jpassSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpassSenha.setText("admin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dialeto:");

        jtextDataBase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextDataBaseActionPerformed(evt);
            }
        });

        jtextPorta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Porta:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bd");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Jdbc:");

        jtext_jdbc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "org.hibernate.dialect.MySQLDialect", "org.hibernate.dialect.MySQL57Dialect", "org.hibernate.dialect.MySQL8Dialect" }));

        jLabel27.setText("Schema:");

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox9, 0, 535, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtextDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel27)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField5)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jtextUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jtext_jdbc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jtextPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jpassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtext_jdbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtextUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtextPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtextDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Principal", jPanel1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Max Size:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Min. Size:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Time Out:");

        jtext_mas_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtext_mas_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_mas_sizeActionPerformed(evt);
            }
        });

        jtext_Min_Size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtext_Time_Out.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Max statements:");

        jtext_Max_Stat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Idle Test Period:");

        jtext_Idle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setText("jLabel7");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(22, 22, 22)
                        .addComponent(jtext_mas_size, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtext_Min_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(jtext_Time_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(26, 26, 26))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(90, 90, 90)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jtext_Max_Stat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtext_Idle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtext_mas_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jtext_Max_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtext_Min_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jtext_Idle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtext_Time_Out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("C3po", jPanel2);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Show Sql:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Format Sql:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Generate Statistics:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Use Sql Coments:");

        jcb_USC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_USC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Não Declarado->", "false", "true" }));
        jcb_USC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_USCActionPerformed(evt);
            }
        });

        jcb_GS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_GS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Não Declarado->", "false", "true" }));
        jcb_GS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_GSActionPerformed(evt);
            }
        });

        jcb_Format_Sql.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_Format_Sql.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Não Declarado->", "false", "true" }));
        jcb_Format_Sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_Format_SqlActionPerformed(evt);
            }
        });

        jcb_Show_Sql.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_Show_Sql.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Não Declarado->", "false", "true" }));
        jcb_Show_Sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_Show_SqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_Show_Sql, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_Format_Sql, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_GS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_USC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jcb_Show_Sql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jcb_Format_Sql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jcb_GS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jcb_USC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Debug ", jPanel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DDL:");

        jcb_ddl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_ddl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Nao Declarado->", "hibernate.hbm2ddl.auto" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Opção DDL:");

        jcb_operacao_ddl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcb_operacao_ddl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Nao Declarado->", "update", "validate", "create", "createdrop" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_operacao_ddl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64)
                        .addComponent(jcb_ddl, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_ddl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_operacao_ddl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opcoes DDL", jPanel4);

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jLabel21.setText("Servidor:");

        jLabel23.setText("Método:");

        jTextField2.setText("jTextField2");

        jLabel22.setText("Porta:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Servidor Hora");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cliente Hora");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servidor Hora", jPanel8);

        jButton13.setText("jButton13");

        jButton14.setText("jButton14");

        jButton15.setText("jButton15");

        jTextField8.setText("jTextField8");

        jLabel26.setText("jLabel26");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jTextField6.setText("jTextField6");

        jTextField9.setText("jTextField9");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(44, 44, 44)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(537, 537, 537)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Backup", jPanel9);

        jbt_salvarConf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt_salvarConf.setText("Salvar Configurações");
        jbt_salvarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salvarConfActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Testar Conexão");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTableBasico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Arquivos", "Data Criacao", "Modificação", "Hash", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBasico.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(jTableBasico);
        if (jTableBasico.getColumnModel().getColumnCount() > 0) {
            jTableBasico.getColumnModel().getColumn(0).setResizable(false);
            jTableBasico.getColumnModel().getColumn(1).setResizable(false);
            jTableBasico.getColumnModel().getColumn(2).setResizable(false);
            jTableBasico.getColumnModel().getColumn(3).setResizable(false);
            jTableBasico.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton12.setText("jButton12");

        jButton16.setText("jButton16");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Arquivos Conexao Basica", jPanel5);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setComponentPopupMenu(jPopupMenu2);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("C3p)", jPanel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Opcoes DDL", jPanel7);

        jButton10.setText("Recarregar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_salvarConf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbt_salvarConf)
                    .addComponent(jButton3)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtextDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextDataBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextDataBaseActionPerformed

    private void jbt_salvarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salvarConfActionPerformed
  
    escritaDadosDDL.SalvaDadosDDL(
    jcb_ddl.getSelectedItem().toString(), 
    jcb_operacao_ddl.getSelectedItem().toString());
         

  escritaDadosC3pO.SalvaConfC3po(
        jtext_mas_size.getText(),
        jtext_Min_Size.getText(),
        jtext_Time_Out.getText(),
        jtext_Max_Stat.getText(),
        jtext_Idle.getText(),
        jTextField1.getText());  
  
  
escritaDadosDebug.
    SalvaConfDebug(
    jcb_Show_Sql.getSelectedItem().toString(), 
    jcb_Format_Sql.getSelectedItem().toString(), 
    jcb_GS.getSelectedItem().toString(), 
    jcb_USC.getSelectedItem().toString());

      WrConfs.
      SalvaConfPersistence(
      jtext_jdbc.getText()+"//",
      jtextUrl.getText(), 
      jtextPorta.getText(), 
      jComboBox1.getSelectedItem().toString(), 
      jComboBox2.getSelectedItem().toString(), 
      jtextDataBase.getText(), 
      jtextUser.getText(),
      jpassSenha.getText());
    }//GEN-LAST:event_jbt_salvarConfActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 if(jComboBox1.getSelectedItem().toString().equals("com.mysql.jdbc.Driver"))
     {
     strDriverBd = jComboBox1.getSelectedItem().toString();
     jtext_jdbc.setText("jdbc:mysql:");
     strJdbc = jtext_jdbc.getText();
     }
     else if(jComboBox1.getSelectedItem().toString().equals("org.postgresql.Driver"))
     {
     strDriverBd = jComboBox1.getSelectedItem().toString();
     jtext_jdbc.setText("jdbc:postgresql:");
     strJdbc = jtext_jdbc.getText();
     }
     else if (jComboBox1.getSelectedItem().toString().equals("org.firebirdsql.jdbc.FBDriver"))
     {
     strDriverBd = jComboBox1.getSelectedItem().toString();
     jtext_jdbc.setText("jdbc:firebirdsql:");
     strJdbc = jtext_jdbc.getText();
     } 
     else if(jComboBox1.getSelectedItem().toString().equals("<-Seleciona o Driver Correspondente ao Servidor->"))
     {
     
     }else{
     
     
     }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
lerDadosSystem.leituraFiles(); 

lerDadosTi.confirmaTi();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtextUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextUrlActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtext_mas_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_mas_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_mas_sizeActionPerformed

    private void jcb_Show_SqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_Show_SqlActionPerformed
if(jcb_Show_Sql.getSelectedItem().equals("<-Não Declarado->"))
{
bshowsql = "<-Não Declarado->";
}
else if(jcb_Show_Sql.getSelectedItem().equals("true"))
{
bshowsql = "true";
}
else if(jcb_Show_Sql.getSelectedItem().equals("false"))
{
bshowsql = "false";
}

    }//GEN-LAST:event_jcb_Show_SqlActionPerformed

    private void jcb_Format_SqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_Format_SqlActionPerformed
if(jcb_Format_Sql.getSelectedItem().equals("<-Não Declarado->"))
{
bforsql = "<-Não Declarado->";
}
else if(jcb_Format_Sql.getSelectedItem().equals("true"))
{
bforsql = "true";
}
else if(jcb_Format_Sql.getSelectedItem().equals("false"))
{
bforsql = "false";
}
    }//GEN-LAST:event_jcb_Format_SqlActionPerformed

    private void jcb_GSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_GSActionPerformed
if(jcb_GS.getSelectedItem().equals("<-Não Declarado->"))
{
gs = "<-Não Declarado->";
}
else if(jcb_GS.getSelectedItem().equals("true"))
{
gs = "true";
}

else if(jcb_GS.getSelectedItem().equals("false"))
{
gs = "false";
}

    }//GEN-LAST:event_jcb_GSActionPerformed

    private void jcb_USCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_USCActionPerformed
 if(jcb_USC.getSelectedItem().equals("true"))
{
usqc = "true";
}

else if(jcb_USC.getSelectedItem().equals("false"))
{
usqc = "false";
}

else if(jcb_USC.getSelectedItem().equals("<-Não Declarado->"))
{
usqc = "<-Não Declarado->";
}

    }//GEN-LAST:event_jcb_USCActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
ler_fTime();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public void ler_fTime(){

          jTableBasico.getColumnModel().getColumn(0).setPreferredWidth(230);
          jTableBasico.getColumnModel().getColumn(1).setPreferredWidth(100);
        
          DefaultTableModel modeloT = (DefaultTableModel)jTableBasico.getModel();
       
          String fTime = "./dist";
             try
              {
                    File fileTime = new File (fTime);
                    String fileTimes[]  = fileTime.list();
                    for(String t : fileTimes)
                    {
                        
                    File o = new File (t);
                    int  numeroLinhas = modeloT.getRowCount();
                    String filtro = o.getName();
                    int tmt = filtro.length();
                    String filtrado = filtro.substring((tmt-4), tmt);
                    String filnome = filtro.substring(0, (tmt-5));
//                    
                  //  File g = new File("./dist"+"/"+filnome+filtrado);
//
//         DateFormat formatDatacr = new SimpleDateFormat("dd/MM/yyyy");
//         String datag = formatDatacr.format(new Date("./dist"+"/"+o.lastModified()));
//                    
//                    
//            //   DateFormat formatDatacr = new SimpleDateFormat("dd/MM/yyyy");
//        // String data = formatDatacr.format(new Date(diretorio.lastModified()));
//        // SimpleDateFormat formatHora = new SimpleDateFormat("HH:mm:ss");
//         //String hora = formatHora.format(new Date(diretorio.lastModified()));
//         Date date2 = (Date)formatDatacr.parse(datag);
         
                   //     System.out.println(datag);
         
//         
         
         
         
         
                                if (filtrado.equals(".nbx"))
                               {

                                   modeloT.addRow(new Object[]{o.getName().toString()});
                      
                               }else{
                           }
                                System.out.println(filtrado);
                    }
               }
             catch(Exception e){
                   JOptionPane.showMessageDialog(null, "NÃO FOI POSSIVEL CARREGAR HORÁRIOS DE BACKUP"+"\n"+"INFORME AO SUPORTE"+e);

               }
        }


    public void carregaArquivos(){
        int opcao;
                   Object[] botoes = {" SIM "," NÃO "};
                   opcao = JOptionPane.showOptionDialog(null, "CONFIRMA EXCLUSÃO DESTE(S) HORÁRIO(S)?", "PERGUNTA DO SISTEMA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,botoes,botoes[0]);
                   if (opcao ==  JOptionPane.YES_OPTION) {

        jTableBasico.getColumnModel().getColumn(0).setPreferredWidth(230);
        //jt_horarios.getColumnModel().getColumn(1).setPreferredWidth(0);
        DefaultTableModel modeloRH = (DefaultTableModel)jTableBasico.getModel();

        int rha[] = jTableBasico.getSelectedRows();
        int jColunnTable = 1;

          for(int t =0; t < rha.length;t++)
          {

            int k = rha[t]-t;
              
              Object obl = jTableBasico.getValueAt(k, jColunnTable);
              String dirTime = String.valueOf(obl);
              modeloRH.removeRow(k);
              System.out.println(dirTime);
          try
            {
            File rem = new File (dirTime);
            if(rem.exists())
            {
              rem.delete();   
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
          }}}          
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JComboBox<String> jComboBox1;
    private static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableBasico;
    private static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbt_salvarConf;
    private static javax.swing.JComboBox<String> jcb_Format_Sql;
    private static javax.swing.JComboBox<String> jcb_GS;
    private static javax.swing.JComboBox<String> jcb_Show_Sql;
    private static javax.swing.JComboBox<String> jcb_USC;
    private static javax.swing.JComboBox<String> jcb_ddl;
    private static javax.swing.JComboBox<String> jcb_operacao_ddl;
    private javax.swing.JPasswordField jpassSenha;
    private static javax.swing.JTextField jtextDataBase;
    private static javax.swing.JTextField jtextPorta;
    private static javax.swing.JTextField jtextUrl;
    private static javax.swing.JTextField jtextUser;
    private static javax.swing.JTextField jtext_Idle;
    private static javax.swing.JTextField jtext_Max_Stat;
    private static javax.swing.JTextField jtext_Min_Size;
    private static javax.swing.JTextField jtext_Time_Out;
    private static javax.swing.JTextField jtext_jdbc;
    private static javax.swing.JTextField jtext_mas_size;
    // End of variables declaration//GEN-END:variables

   public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(frameConfigBDView == null) 
                frameConfigBDView= new JFrame();
                frameConfigBDView.setContentPane(new ConfigBDView());
                frameConfigBDView.setSize(560, 369);//[644, 578][][]
                frameConfigBDView.setResizable(false);
                frameConfigBDView.setLocationRelativeTo(null);
                frameConfigBDView.pack();
                frameConfigBDView.setVisible(true);
                frameConfigBDView.setTitle(args[0]); 
             
                jtextUrl.setText(lerDadosSystem.textDoneUrlServidor);
                jtextPorta.setText(lerDadosSystem.textDoneParPortDb);
                jtextDataBase.setText(lerDadosSystem.textDoneParDatabase);
                jtextUser.setText(lerDadosSystem.textDoneParLogin);
                
                     // Por teste de strings SETA o index DO COMBOBOX ATRAVÉZ classe "lerDadosSystem"
                     //de leitura do DRIVER da Conexao no componentes Swings   
                    if(lerDadosSystem.textDoneParDriverDb.equals("<-Seleciona o Driver Correspondente ao Servidor->"))
                    {
                    jComboBox1.setSelectedIndex(0); 
                    }
                    else if(lerDadosSystem.textDoneParDriverDb.equals("com.mysql.jdbc.Driver"))
                    {
                    jComboBox1.setSelectedIndex(1); 
                    }
                    else if(lerDadosSystem.textDoneParDriverDb.equals("com.mysql.cj.jdbc.Driver"))
                    {
                    jComboBox1.setSelectedIndex(2);
                    }
                    else if(lerDadosSystem.textDoneParDriverDb.equals("org.postgresql.Driver"))
                    {
                    jComboBox1.setSelectedIndex(3);
                    }
                    else if(lerDadosSystem.textDoneParDriverDb.equals("org.firebirdsql.jdbc.FBDriver"))
                    {
                    jComboBox1.setSelectedIndex(4);
                    }

                    if(lerDadosSystem.textDoneParDialetoDb.equals("<-Selecione um Dialeto->"))
                    {
                    jComboBox2.setSelectedIndex(0); 
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.FirebirdDialectt"))
                    {
                    jComboBox2.setSelectedIndex(1);
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.MySQLDialect"))
                    {
                    jComboBox2.setSelectedIndex(2); 
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.MySQL57Dialect"))
                    {
                    jComboBox2.setSelectedIndex(3);
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.MySQL8Dialect"))
                    {
                     jComboBox2.setSelectedIndex(4);
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.PostgreSQL81Dialect"))
                    {
                    jComboBox2.setSelectedIndex(5); 
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.PostgreSQL82Dialect"))
                    {
                    jComboBox2.setSelectedIndex(6);
                    }
                    else if(lerDadosSystem.textDoneParDialetoDb.equals("org.hibernate.dialect.PostgreSQL9Dialect"))
                    {
                     jComboBox2.setSelectedIndex(7);
                    }


                            if(lerDadosDebug.textDoneShow_Sql.equals("true"))
                            {
                            jcb_Show_Sql.setSelectedIndex(2);
                              //  System.out.println("entrou no if o valor do Show Sql é:" +lerDadosDebug.textDoneShow_Sql);
                            }
                            else if(lerDadosDebug.textDoneShow_Sql.equals("false"))
                            {
                            jcb_Show_Sql.setSelectedIndex(1);
                          //  System.out.println("entrou no if o valor do Show Sql é:" +lerDadosDebug.textDoneShow_Sql);
                            }
                            if(lerDadosDebug.textDoneShow_Sql.equals("<-Não Declarado->"))
                            {
                            jcb_Show_Sql.setSelectedIndex(0);
                          //  System.out.println("entrou no if o valor do Show Sql é:" +lerDadosDebug.textDoneShow_Sql);
                            }
                            
//                            
                            if(lerDadosDebug.textDoneFormat_Sql.equals("false"))
                            {
                            jcb_Format_Sql.setSelectedIndex(1);
                            }
                            else if(lerDadosDebug.textDoneFormat_Sql.equals("true"))
                            {
                            jcb_Format_Sql.setSelectedIndex(2);
                            }
                            else if(lerDadosDebug.textDoneFormat_Sql.equals("<-Não Declarado->"))
                            {
                            jcb_Format_Sql.setSelectedIndex(0);
                            }
                            
                            
                            
                            
                             if(lerDadosDebug.textDoneGS.equals("<-Não Declarado->"))
                            {
                            jcb_GS.setSelectedIndex(0);
                            }
                            
                             else if(lerDadosDebug.textDoneGS.equals("true"))
                            {
                            jcb_GS.setSelectedIndex(2);
                            }
                            
                              else if(lerDadosDebug.textDoneGS.equals("false"))
                            {
                            jcb_GS.setSelectedIndex(1);
                            }
                             
                              if(lerDadosDebug.textDoneUSC.equals("<-Não Declarado->"))
                            {
                            jcb_USC.setSelectedIndex(0);
                            }
                            
                             else if(lerDadosDebug.textDoneUSC.equals("true"))
                            {
                            jcb_USC.setSelectedIndex(2);
                            }
                            
                              else if(lerDadosDebug.textDoneUSC.equals("false"))
                            {
                            jcb_USC.setSelectedIndex(1);
                            }
                        
                              
                              if (lerDadosDDL.textDoneddl.equals("<-Não Declarado->"))
                              {
                                  jcb_ddl.setSelectedIndex(0);
                              }
                              else if(lerDadosDDL.textDoneddl.equals("hibernate.hbm2ddl.auto"))
                              {
                                     jcb_ddl.setSelectedIndex(1);
                              }
                              
                            if (lerDadosDDL.textDoneopddl.equals("<-Não Declarado->"))
                              {
                                  jcb_operacao_ddl.setSelectedIndex(0);
                              }
                              else if(lerDadosDDL.textDoneopddl.equals("update"))
                              {
                                     jcb_operacao_ddl.setSelectedIndex(1);
                              }
                             else if(lerDadosDDL.textDoneopddl.equals("validate"))
                              {
                                     jcb_operacao_ddl.setSelectedIndex(2);
                              }
                             else if(lerDadosDDL.textDoneopddl.equals("create"))
                              {
                                     jcb_operacao_ddl.setSelectedIndex(3);
                              }
                             else if(lerDadosDDL.textDoneopddl.equals("createdrop"))
                              {
                                     jcb_operacao_ddl.setSelectedIndex(4);
                              }
  
                            else if(lerDadosDebug.textDoneShow_Sql.equals("false"))
                            {
                            jcb_Format_Sql.setSelectedItem(1);
                            }
                            else if(lerDadosDebug.textDoneShow_Sql.equals("<-Não Declarado->"))
                            {
                            jcb_Format_Sql.setSelectedItem(0);
                            }
                                  
//                            
//                            if(lerDadosDebug.textDoneGS.equals("true"))
//                            {
//                            jcb_GS.setSelectedItem(2);
//                            }
//                            
//                            else if(lerDadosDebug.textDoneGS.equals("false"))
//                            {
//                            jcb_GS.setSelectedItem(1);
//                            }
//                            else if(lerDadosDebug.strDoneShow_Sql.equals("<-Não Declarado->"))
//                            {
//                            jcb_GS.setSelectedItem(0);
//                            }
//                            
//                            
//                            if(lerDadosDebug.strDoneUSC.equals("true"))
//                            {
//                            jcb_USC.setSelectedItem(2);
//                            }
//                            
//                            else if(lerDadosDebug.strDoneUSC.equals("false"))
//                            {
//                            jcb_USC.setSelectedItem(1);
//                            }
//                            else if(lerDadosDebug.strDoneUSC.equals("<-Não Declarado->"))
//                            {
//                            jcb_USC.setSelectedItem(0);
//                            }              
                            jtext_mas_size.setText(lerDadosSystem.textDoneC3p0_max_size);
                            jtext_Min_Size.setText(lerDadosSystem.textDoneC3p0_min_size);
                            jtext_Time_Out.setText(lerDadosSystem.textDoneC3p0_timeout);
                            jtext_Max_Stat.setText(lerDadosSystem.textDoneC3p0_max_statements);
                            jtext_Idle.setText(lerDadosSystem.textDoneC3p0_idle_test_period);
                            jTextField1.setText(lerDadosSystem.textDoneC3p0_acquire_increment);

            }
        });
    }



}
